# Generated by Django 4.2.6 on 2024-03-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeitem', '0002_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
