# Generated by Django 4.2.6 on 2024-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeitem', '0007_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(blank=True, null=True, upload_to='variation_images/'),
        ),
    ]
