# Generated by Django 4.2.6 on 2024-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('Damage', 'Item is damaged'), ('Wrong Size', 'Wrong size ordered'), ('Wrong Item', 'Wrong item received'), ('Other', 'Other reason')], max_length=100)),
            ],
        ),
    ]
