# Generated by Django 4.2.6 on 2024-05-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
