# Generated by Django 4.2.6 on 2024-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeitem', '0004_variation'),
        ('cart', '0002_rename_card_id_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='storeitem.variation'),
        ),
    ]
