# Generated by Django 4.2.6 on 2024-04-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_order_id_coupon_order_and_more'),
        ('cart', '0007_cartitem_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='coupons.coupon'),
        ),
    ]
