# Generated by Django 4.2.6 on 2024-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
