# Generated by Django 4.2.6 on 2024-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_coupon_is_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_out_of_stock',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
