# Generated by Django 4.2.6 on 2024-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartitem_cart_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
