# Generated by Django 4.2.6 on 2024-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='order_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
