# Generated by Django 4.2.6 on 2024-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomOrder',
        ),
    ]
