# Generated by Django 4.2.6 on 2024-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_addresses_order_note_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreportnew',
            name='total_coupon_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
