# Generated by Django 4.2.6 on 2024-06-10 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_salesreportnew_total_coupon_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreportnew',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='orders.order'),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='order_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Not_Completed', 'Not_Completed')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesreportnew',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
