# Generated by Django 4.2.6 on 2024-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='return_reason',
            field=models.CharField(max_length=100),
        ),
    ]
