# Generated by Django 4.2.6 on 2024-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_returnrequest_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_reason',
            field=models.TextField(),
        ),
    ]
