# Generated by Django 4.2.6 on 2024-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderproduct_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
