# Generated by Django 4.2.6 on 2024-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_returnrequest_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
