# Generated by Django 4.2.6 on 2024-05-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponStats',
            fields=[
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.coupon')),
                ('coupon_count', models.PositiveIntegerField(default=0)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
