# Generated by Django 4.2.6 on 2024-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_couponstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
