# Generated by Django 4.2.6 on 2024-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_coupon_count_order_coupon_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReportNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sales_count', models.IntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_coupon_count', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
