# Generated by Django 4.2.6 on 2024-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_salesreportnew_total_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreportnew',
            name='overall_sales_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreportnew',
            name='total_coupon_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
