# Generated by Django 4.2.6 on 2024-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_salesreportnew_overall_sales_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreportnew',
            name='overall_sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreportnew',
            name='total_coupon_count',
            field=models.IntegerField(default=0),
        ),
    ]
