# Generated by Django 4.2.6 on 2024-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_salesreportnew_overall_sales_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreportnew',
            name='overall_sales_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreportnew',
            name='total_coupon_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreportnew',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salesreportnew',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
