# Generated by Django 4.2.6 on 2024-05-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_salesreportnew_overall_sales_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponStats',
        ),
    ]
